openapi: 3.0.1
info:
    title: Bookker_API_ext
    description: This is the definition of Bookker API REST
    termsOfService: https://webapiext.bookkercorp.com/terms.html
    license:
      name: BOOKKER CORPORATE SL
      url: https://webapiext.bookkercorp.com/terms.html
    contact:
      name: Bookker API Support
      url: https://www.bookkercorp.com/contacto
      email: bookkersupport@bookkercorp.com
    version: 1.0.0  
servers:
- url: https://private-4ea1f-bookkerprueba.apiary-mock.com
  description: Mock Server - no credentials requiered
- url: https://apis.develop.bookkercorp.com
  description: Dev Server - Auth credentials requiered  
- url: https://apis.bookkercorp.com
  description: Prod Server - Auth credentials requiered
security:
    - api-key: [] 
    - OAuth2: [] #here inside the brakets, the list the scopes required in the security section
paths:
  /reports/v1/pastbookings/yesterday:
    get:
      tags:
      - reports-pastbooking-controller
      summary: Returns bookings for a period of one day
      operationId: lastDay
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 500
      responses:
        "200":
          description: Success returning bookings from history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePastBookingResponse'
        "400":
          description: Parameters page and size must be greater than 0 and size less or equal to 500
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorView'
  /reports/v1/pastbookings/last7days:
    get:
      tags:
      - reports-pastbooking-controller
      summary: Returns bookings for a period of 7 days
      operationId: lastWeek
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 500
      responses:
        "200":
          description: Success returning bookings from history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePastBookingResponse'
        "400":
          description: Parameters page and size must be greater than 0 and size less or equal to 500
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorView'
  /reports/v1/pastbookings/last15days:
    get:
      tags:
      - reports-pastbooking-controller
      summary: Returns bookings for a period of 15 days
      operationId: lastFortnight
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 500
      responses:
        "200":
          description: Success returning bookings from history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePastBookingResponse'
        "400":
          description: Parameters page and size must be greater than 0 and size less or equal to 500
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorView'             
  /reports/v1/pastbookings/last30days:
    get:
      tags:
      - reports-pastbooking-controller
      summary: Returns bookings for a period of 30 days
      operationId: lastMonth
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 500
      responses:
        "200":
          description: Success returning bookings from history
            indicado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePastBookingResponse'
        "400":
          description: Parameters page and size must be greater than 0 and size less or equal to 500
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorView'          
  /reports/v1/pastbookings/period:
    get:
      tags:
      - reports-pastbooking-controller
      summary: Returns historic bookings for a period between two dates specified in the parameters to and from
      operationId: customPastPeriod
      parameters:
      - name: from
        in: query
        required: true
        schema:
          type: string
      - name: to
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 500
      responses:
        "200":
          description: Success returning bookings from history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePastBookingResponse'
        "400":
          description: Parameters page and size must be greater than 0 and size less or equal to 500
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorView'          
  /reports/v1/futurebookings/period:
    get:
      tags:
      - reports-futurebooking-controller
      summary: Returns active bookings for a period between two dates specified in the parameters to and from
      operationId: customPeriod
      parameters:
      - name: from
        in: query
        required: true
        schema:
          type: string
      - name: to
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 500
      responses:
        "200":
          description: Success returning active bookings
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CreateFutureBookingResponse'
        "400":
          description: Parameters page and size must be greater than 0 and size less or equal to 500
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorView'
  /bookings/v1/checkin/{bookingId}:
      post:
        tags:
        - check-in-controller
        operationId: externalCheckInBooking
        parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
        - name: presenceValidation
          in: query
          required: false
          schema:
            type: string
        - name: userId
          in: query
          required: false
          schema:
            type: string
        - name: x-on-behalf-of
          in: header
          required: false
          schema:
            type: string
        responses:
          "200":
            description: Check-in of the booking was completed 
          "403":
            description: User has no access
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorView'
          "404":
            description: No resource has been found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorView'
          "400":
            description: Check-out of the booking couldn't be completed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorView'
          "409":
            description: The request is not correct
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorView'
  /bookings/v1/checkout/{bookingId}:
      post:
        tags:
        - check-in-controller
        operationId: externalCheckOutBooking
        parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: query
          required: false
          schema:
            type: string
        - name: x-on-behalf-of
          in: header
          required: false
          schema:
            type: string
        responses:
          "200":
            description: Check-out of the booking was completed        
          "403":
            description: User has no access
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorView'
          "404":
            description: No resource has been found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorView'
          "409":
            description: Check-out of the booking couldn't be completed
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorView'
          "400":
            description: The request is not correct
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorView'
components:
  schemas:
    CreatePastBookingResponse:
      type: object
      properties:
        bookings:
          type: array
          items:
            $ref: '#/components/schemas/ReportHisBookingResponse'
    FloorResponse:
      required:
      - name
      type: object
      properties:
        name:
          maxLength: 255
          minLength: 0
          type: string
    ReportHisBookingResponse:
      required:
      - bookingId
      - endDate
      - floor
      - organizer
      - resource
      - startDate
      - status
      type: object
      properties:
        bookingId:
          type: string
        createdDate:
          type: string
          format: date-time
        organizer:
          $ref: '#/components/schemas/UserResponse'
        vehicle:
          $ref: '#/components/schemas/VehicleResponse'
        floor:
          $ref: '#/components/schemas/FloorResponse'
        resource:
          $ref: '#/components/schemas/ResourceResponse'
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        status:
          type: string
          enum:
          - PENDING
          - PENDING_APPROVAL
          - CONFIRMED
          - CANCELLED
          - EXPIRED
          - FINISHED
          - PENDING_ASSIGNMENT
          - PENDING_VOTING
          - UNDETERMINED
    CreateFutureBookingResponse:
      type: object
      properties:
        bookings:
          type: array
          items:
            $ref: '#/components/schemas/ReportFutureBookingResponse'
    ReportFutureBookingResponse:
      required:
      - bookingId      
      - endDate
      - floor
      - organizer
      - resource
      - startDate
      - status
      type: object
      properties:
        bookingId:
          type: string      
        createdDate:
          type: string
          format: date-time
        organizer:
          $ref: '#/components/schemas/UserResponse'
        vehicle:
          $ref: '#/components/schemas/VehicleResponse'
        floor:
          $ref: '#/components/schemas/FloorResponse'
        resource:
          $ref: '#/components/schemas/ResourceResponse'
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        status:
          type: string
          enum:
          - PENDING
          - PENDING_APPROVAL
          - CONFIRMED
          - CANCELLED
          - EXPIRED
          - FINISHED
          - PENDING_ASSIGNMENT
          - PENDING_VOTING
          - UNDETERMINED
    ResourceResponse:
      type: object
      properties:
        posterCode:
          type: string
    UserResponse:
      required:
      - email
      - name
      - surname
      type: object
      properties:
        name:
          maxLength: 255
          minLength: 0
          type: string
        surname:
          maxLength: 255
          minLength: 0
          type: string
        email:
          maxLength: 255
          minLength: 0
          type: string
    VehicleResponse:
      type: object
      properties:
        licensePlate:
          maxLength: 255
          minLength: 0
          type: string    
    ErrorView:
      type: object
      properties:
        uniqueId:
          type: string
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        errors:
          type: array
          items:
            type: string
        type:
          type: string
        path:
          type: string
        message:
          type: string
        microsoftErrorCode:
          type: string 
  securitySchemes:
    api-key:
        type: apiKey
        description: API key to authorize requests
        name: x-api-key
        in: header
    OAuth2:
      type: oauth2
      description: This API uses OAuth 2 with the CLIENT CREDENTIALS grant flow 
      flows:
        clientCredentials:
          tokenUrl: https://bookker-dev.auth.eu-west-1.amazoncognito.com/oauth2/token
          scopes:
              https://apis.bookkercorp.com/resource.read: read resources Prod
              https://apis.develop.bookkercorp.com/resource.read: read resources Dev